name: anamil
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.8.3
  shared_preferences: ^2.2.0
  flutter_rating_stars: ^1.0.3+4
  flutter_rating_bar: ^4.0.1
  fluttertoast:
  flutter_bloc: ^8.1.1
  bloc:
  font_awesome_flutter: ^10.5.0
  carousel_slider: ^4.2.1
  dropdown_search: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: GE_SS
      fonts:
        - asset: assets/fonts/GE_SS_Bold.otf
        - asset: assets/fonts/GE_SS_Two_Light.otf
        - asset: assets/fonts/GE_SS_Two_Medium.otf
